### ISSUE TITLE
How do I mount the service on github pages?

### ISSUE THREAD

**Issue by guaifish** [ljvmiranda921/sprites-as-a-service#74]
I want to mount the service on github pages like you do, mount `sprites-as-a-service/` on `https://ljvmiranda921.github.io/`, how can I do that?

**Comment by ljvmiranda921** [comment]
Hi @guaifish sorry I wasn't able to reply! The way I do this is via Github Actions, you can check how I do it here: https://github.com/ljvmiranda921/sprites-as-a-service/blob/master/.github/workflows/gh-pages.yml

**Comment by guaifish** [comment]
Thanks, I've found a way to do this. I'm new to FastAPI, your project help me a lot.
